#!/bin/bash

# Find the absolute path to CRUSH (follow links manually, not using '-f'
# which does not work on MacOS X)
EXECNAME=$0
while [ -L $EXECNAME ] ; do EXECNAME=`readlink $EXECNAME`; done
CRUSH=`dirname $EXECNAME`

# Configure the runtime settings (classpaths, java runtime options)
source $CRUSH/startup/wrapper.sh crush

# And run CRUSH...
$JAVA $JAVAOPTS -classpath $CLASSPATH crush.CRUSH ${1+"$@"} 


