#!/bin/bash

# Find the absolute path to CRUSH (follow links manually, not using '-f'
# (which does not work on MacOS X)
EXECNAME=$0
while [ -L $EXECNAME ] ; do EXECNAME=`readlink $EXECNAME`; done
CRUSH=`dirname $EXECNAME`

source $CRUSH/wrapper.sh difference

java $JAVAOPTS -classpath $CLASSPATH crushtools.SkyMapDifferencer ${1+"$@"}
