#!/bin/bash

# Find the absolute path to CRUSH (follow links manually, not using '-f'
# (which does not work on MacOS X)
EXECNAME=$0
while [ -L $EXECNAME ] ; do EXECNAME=`readlink $EXECNAME`; done
CRUSH=`dirname $EXECNAME`

source $CRUSH/startup/wrapper.sh esorename

$JAVA $JAVAOPTS -classpath $CLASSPATH crush.apex.ESORename ${1+"$@"} 
