#!/bin/bash

# Find the absolute path to CRUSH (follow links manually, not using '-f'
# (which does not work on MacOS X)
EXECNAME=$0
while [ -L $EXECNAME ] ; do EXECNAME=`readlink $EXECNAME`; done
CRUSH=`dirname $EXECNAME`

source $CRUSH/srartup/wrapper.sh imagetool

$JAVA $JAVAOPTS -classpath $CLASSPATH crushtools.ImageTool ${1+"$@"}
