name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Pack Source JARs
      run: ant -noinput -buildfile crush/eclipse/buildjar.xml
    - name: Build with Ant
      run: ant -noinput -buildfile crush/ant/build.xml
